//HOME
export const FETCH_HOME_ACTION = 'FETCH_HOME_ACTION'
export const FETCH_HOME_ADD = 'FETCH_HOME_ADD'
export const FETCH_HOME_DELETE = 'FETCH_HOME_DELETE'
export const FETCH_HOME_UPDATE = 'FETCH_HOME_UPDATE'





